Update Main from Dev (#58)
* Added support for OAP websites, into oap-1 vcard

* Updated Names and Website Additions (#51)

* Removed Blank nodes in publications.  Works now have pseudo work:999#date node.

* Fixes #42, #43, #44.

* Moved cdl to cdl-elements in that repo.

* Updated VCARD entries for websites. (#53)

* All pages no graph (#55)

* Updated signatures.

* Added page numbers to publications.

* Removed multiple graphs from experts database.

* Fixes #46. Fixes #49.

* Experts graph updates. Added grants.

* Fixed FoR insert query.

* Updated Grants for more careful related links.

* Added AdminRole.

* Authorships only one per-expert. Fixes #56 (#57)

diff --git a/harvest b/harvest
--- a/harvest
+++ b/harvest
@@ -145,6 +145,34 @@ function main.cmd () {
     esac
 }
 
+function log_assoc() {
+  local opts;
+  if ! opts=$(${G[util_getopt]} -o v --long verbose -n 'harvest log_assoc' -- "$@"); then
+    echo "Bad Command Options." >&2 ; exit 1 ; fi
+
+    eval set -- "$opts"
+
+    local log_verbose=0
+
+    while true; do
+	    case $1 in
+	      -v | --verbose) let log_verbose=$log_verbose+1;  shift;;
+	      -- ) shift; break;;
+      esac
+    done
+
+    declare -n v=$1
+    v[exe]="harvest"
+    v[timestamp]="$(date --iso-8601=seconds)"
+
+    if (( ${G[verbose]} >= $log_verbose )) ; then
+      for key in "${!v[@]}"; do
+        printf '%s\0%s\0' "$key" "${v[$key]}"
+      done |
+        jq -Rsc ' split("\u0000") | . as $a | reduce range(0  ; length/2) as $i  ({}; . + {($a[  2*$i]): ($a[2*$i + 1]|fromjson? // .)})'
+    fi
+}
+
 function log() {
   local opts;
   if ! opts=$(${G[util_getopt]} -o nv --long verbose -n 'harvest log' -- "$@"); then
@@ -219,6 +247,10 @@ function db() {
   local auth=${G[fuseki_auth]}
   local dbs=()
 
+  declare -A logit=(
+    [cmd]="db $1"
+    );
+
   cmd=$1
   shift;
 
@@ -233,7 +265,9 @@ function db() {
       while [[ -n "$1" ]]; do
         dbs+=($(http --auth=${auth} DELETE ${G[fuseki_admin]}/harvestdb?name="$1" | tr -d '\r'))
         if [[ -d ${G[harvest_base]}/"$1" ]]; then
-          log -v "rm -rf ${G[harvest_base]}/$1"
+          logit[cmd]+=" rm"
+          logit[dir]="${G[harvest_base]}/$1"
+          log_assoc -v logit
           rm -rf "${G[harvest_base]}/$1"
         fi
         shift
@@ -244,7 +278,7 @@ function db() {
         dbs+=($(http --auth=${auth} POST ${G[fuseki_admin]}/harvestdb | tr -d '\r'))
       else
         while [[ -n "$1" ]]; do
-          dbs+=($(http --auth=${auth} POST ${G[fuseki_admin]} /harvestdb?name="$1" | tr -d '\r'))
+          dbs+=($(http --auth=${auth} POST ${G[fuseki_admin]}/harvestdb?name="$1" | tr -d '\r'))
           shift
         done
       fi
@@ -252,7 +286,7 @@ function db() {
     *) err "Invalid command $cmd"
        ;;
   esac
-  echo "${dbs[@]}"
+  echo $dbs
 }
 
 
@@ -294,9 +328,7 @@ function login() {
 	local v_s
   v_s=$(for i in $(seq ${G[verbose]} ); do echo -n " -v"; done)
 
-	log -v -n "cdl."
-	cdl ${v_s} login --auth=${CMD[cdl_auth]}
-	log -v -n "ucdid."
+	cdl-elements ${v_s} login --auth=${CMD[cdl_auth]}
 	ucdid ${v_s} login --auth=${CMD[ucdid_auth]}
 }
 
@@ -311,11 +343,11 @@ harvest I<global_options> B<user> I<options>
 Run a complete harvest operation for a particular ucdid search.  This command
 will first initialize a HARVEST_DB if one does not exist.  Then the program will
 query the C<ucdid> with the the passed C<--search> query, and collect a set of
-users.  It will then contact the CDL elements database (via the cdl command) and
-download all user and publication information for these users.  Then the command
-will run a series of sparql updates (via C<harvest update>) to update the
-experts database.  The command will then clean up, by removing the HARVEST_DB,
-and the cache of files downloaded from the services.
+users.  It will then contact the CDL elements database (via the cdl-elements
+command) and download all user and publication information for these users.
+Then the command will run a series of sparql updates (via C<harvest update>) to
+update the experts database.  The command will then clean up, by removing the
+HARVEST_DB, and the cache of files downloaded from the services.
 
 =over 4
 
@@ -354,6 +386,7 @@ function user () {
   if ! opts=$(${G[util_getopt]} -o is:rnm: --long init,no-init,search:,remove,no-remove,last-modified -n 'harvest load' -- "$@"); then
     echo "Bad Command Options." >&2 ; exit 1 ; fi
 
+  local begin=$SECONDS
   eval set -- "$opts"
 
   declare -A CMD=(
@@ -362,6 +395,9 @@ function user () {
     [remove]=1
     [modified]=''
     );
+
+  declare -A logit=(
+    [cmd]="user");
 
   while true; do
 	  case $1 in
@@ -380,20 +416,20 @@ function user () {
     err 1 "harvest run, must specify a --search parameter.  See ucdid for details."
   fi
 
-  if [[ -n ${CMD[init]} || -z ${G[db]} ]]; then
+  if [[ -n ${CMD[init]} || -z ${G[harvest_db]} ]]; then
     G[harvest_db]=$(db new);
   fi
 	local ep=${G[fuseki_host]}/${G[harvest_db]}
 
-  if ${CMD[fetch]} ; then
+   if ${CMD[fetch]} ; then
     # Now fetch all the data w/ CDL
     local cache=${G[harvest_base]}/${G[harvest_db]}
-	  log -v -v "cache: $cache"
+	  #log -v -v "cache: $cache"
     mkdir $cache;
   fi
     # call UCDID w/ query
     local profiles_ttl=$cache/profiles.ttl
-    log -v -v "ucdid fetch --format=ttl --search=\"${CMD[search]}\" profiles > $profiles_ttl"
+    #log -v -v "ucdid fetch --format=ttl --search=\"${CMD[search]}\" profiles > $profiles_ttl"
     ucdid fetch --format=ttl --search="${CMD[search]}" profiles > $profiles_ttl
     load --graph=http://iam.ucdavis.edu/ $profiles_ttl
 
@@ -403,22 +439,24 @@ function user () {
   # Now get all the casIDs, This doesn't use experts, but the harvestdb
   ids="$(aeq --endpoint="$ep"/sparql query --format=json <<<"select ?id where { {graph harvest_iam: {?u iam:userID ?id; filter(NOT EXISTS {?u iam:directory ?d }) } } UNION { graph harvest_iam: {[] iam:userID ?id; iam:directory/iam:displayName/iam:nameWwwFlag 'Y'. }}} order by ?id" | jq -r .results.bindings[].id.value | tr [:space:] ' ')"
 
-  log -v "cdl for ids='$ids'"
-
 	local v_s
   v_s="$(for i in $(seq ${G[verbose]} ); do echo -n " -v"; done)"
-  cdl $v_s --cache=$cache --data=$ep users --pubs $ids
+  cdl-elements $v_s --cache=$cache --data=$ep/data users --pubs $ids
 
   # Then, run the update scripts for new data
   update update_harvest_records
   update experts
   update journal publications authorships
   update pub_FoR pub_free keywords expert_concepts;
+  update grants
 
 	if [[ -n ${CMD[remove]} ]]; then
-		log -v "db rm ${G[harvest_db]};"
+    logit[db]="db rm ${G[harvest_db]};"
 		db rm ${G[harvest_db]}
 	fi;
+  logit[duration]=$(($SECONDS-$begin))
+  log_assoc -v logit
+
 }
 
 : <<='cut'
@@ -453,6 +491,10 @@ function export () {
     [directory]=''
     );
 
+  declare -A logit=(
+    [cmd]="export"
+  );
+
   while true; do
 	  case $1 in
 	    -d | --directory) CMD[directory]=$2;  shift 2;;
@@ -468,8 +510,7 @@ function export () {
 
 	local graphdirs=(
 		experts.ucdavis.edu
-		experts.ucdavis.edu%2Fiam
-		experts.ucdavis.edu%2Foap
+		experts.ucdavis.edu%2Ffis
 	)
 
 	local get=http://fuseki:3030/experts/get
@@ -478,7 +519,8 @@ function export () {
 		local d=${CMD[directory]}/$dir;
 		[[ -d $d ]] || mkdir $d;
 		local g=$(printf 'http://%b/' ${dir//%/\\x})
-		log -v "curl \"${get}?graph=$g\" | gzip > $d/graph.ttl"
+    logit[export]="curl \"${get}?graph=$g\" | gzip > $d/graph.ttl"
+    log_assoc -v logit
     curl -s "${get}?graph=$g" | gzip > $d/graph.ttl.gz
 	done
 
@@ -513,6 +555,10 @@ Run update queries on the fuseki harvestdb endpoint.  I
 function update () {
   local file;
 	local begin;
+  declare -A logit=(
+    [cmd]="update"
+    );
+
   if [[ -n ${G[harvest_db]} ]]; then
     local auth=${G[fuseki_auth]}
     local update=${G[fuseki_host]}/${G[harvest_db]}/update
@@ -524,17 +570,21 @@ function update () {
         file=${G[harvest_home]}/ru/$file;
         [[ -f $file ]] || file=${file}.ru
       fi
+      logit[file]=$file
       if [[ -f $file ]]; then
-				log -v -v "curl -s --location --request POST --user \"${auth}\" -H Content-Type:application/sparql-update --data-binary \"@${file}\" ${update}"
+				#log -v -v "curl -s --location --request POST --user \"${auth}\" -H Content-Type:application/sparql-update --data-binary \"@${file}\" ${update}"
 				begin=$SECONDS
         curl -s --location --request POST --user "${auth}" -H Content-Type:application/sparql-update --data-binary "@${file}" ${update}
-				log -v "update $file time=$(($SECONDS-$begin))"
+        logit[duration]=$(($SECONDS-$begin))
       else
-        log -v "update $file not found"
+        logit[info]="$file not found"
       fi
+      log_assoc -v logit
     done
   else
-    err 1 "No harvest-db specified, via --db= or via HARVEST_DB env. variable."
+    logit[err]="No harvest-db specified, via --db= or via HARVEST_DB env. variable."
+    log_assoc logit
+    err 1
   fi
 }
 
@@ -591,6 +641,8 @@ function load () {
 	local count;
 	local begin;
 
+  declare -A logit=([cmd]="load");
+
   if [[ -n ${G[harvest_db]} ]]; then
     local auth=${G[fuseki_auth]}
     local load=${G[fuseki_host]}/${G[harvest_db]}/data
@@ -603,18 +655,27 @@ function load () {
         fn=$file
       fi
 			begin=$SECONDS
-      log -v -v "curl -s --location --request POST --user ${auth} -H \"Content-Type:multipart/form-data\" -F \"file=@${file};filename=${fn}\" \"${load}?graph=${CMD[graph]}\""
+      #log -v -v "curl -s --location --request POST --user ${auth} -H \"Content-Type:multipart/form-data\" -F \"file=@${file};filename=${fn}\" \"${load}?graph=${CMD[graph]}\""
       count=$(curl -s --location --request POST --user ${auth} -H "Content-Type:multipart/form-data" -F "file=@${file};filename=${fn}" "${load}?graph=${CMD[graph]}" | jq .count)
-			log -v "load $fn graph=${CMD[graph]} count=$count time=$(($SECONDS-$begin))"
+      logit[graph]=${CMD[graph]}
+      logit[fn]=$fn
+      logit[count]=$count
+      logit[duration]=$(($SECONDS-$begin))
+      logit[loader]="${load}"
+      log_assoc -v logit
     done
   fi
   # No can load both
   if [[ -n ${G[tdb]} && false ]]; then
     for file in "$@"; do
       [[ "$file" = '-' ]] && file=/dev/stdin
-      log -v -v "tdb2.tdbloader --loc=${G[tdb]} --graph=${G[graph]} $file"
+      #log -v -v "tdb2.tdbloader --loc=${G[tdb]} --graph=${G[graph]} $file"
       count=$(tdb2.tdbloader --loc=${G[tdb]} --graph=${G[graph]} $file)
-			log -v "tdb $fn graph=${CMD[graph]} => $count"
+      logit[fn]=$fn
+      logit[graph]=${CMD[graph]}
+      logit[count]=$count
+      logit[loader]="tdbloader"
+      log_assoc -v logit
     done
   fi
 }
